### ISSUE TITLE
License Clarity/Request

### ISSUE THREAD

**Issue by chunky** [insongkim/concordance#10]
At my company, we're working to release the code for an R module, but are currently unable to because it depends on this "concodance" module, and the licensing for this is either unclear or "GPLv2"; "GPLv2" [as in, GPLv2-only] is mentioned in the DESCRIPTION metadata file, but nowhere else in the code that I can find, which makes me unsure what the developer's true intent is.

If this code is GPLv2, then that is in conflict with some other modules that we are using, including Apache and GPLv3. If that isn't deliberate, or the code doesn't have any license at all associated with it [which I might infer from the rest of the repo], then I'm not sure what to do.

All of Tidyverse and R-lib have recently undergone a substantial relicensing effort to bring them all in line and make it easier to use them, by changing everything to MIT: https://www.tidyverse.org/blog/2021/12/relicensing-packages/

So, finally, my request: Please can you clarify the licensing on this package? And, ideally, if no other requirements are in place, make that licensing MIT?

**Comment by stevenliaotw** [comment]
Thanks for the question/request. We are looking into the license agreements with our coauthors and will let you know.

**Comment by chunky** [comment]
Thank you for entertaining the discussion!

I don't wish to push if this request is orthogonal to your teams beliefs on software liberty, please don't hesitate to decline if that's the case.

**Comment by stevenliaotw** [comment]
Thanks! Following your request, we have decided to also re-license to MIT. We have made the changes to our developer's version on Github and hope this clarification is sufficient for now. The implementation on CRAN will come at a later date.

**Comment by chunky** [comment]
Fantastic! Thank you!

**Comment by insongkim** [comment]
No problem. We would appreciate it if you could cite our package when you release your code. Thank you very much.

`Steven Liao, In Song Kim, Sayumi Miyano, Hao Zhang (2020). concordance: Product Concordance. 
  R package version 2.0.0. https://CRAN.R-project.org/package=concordance`
