### ISSUE TITLE
NAICS(combined)

### ISSUE THREAD

**Issue by liqizheng0328** [insongkim/concordance#13]
Dear Sir or Madam,

I am Li Qizheng, a master in the University of International Business and Economics, Beijing.

In the function "concord_hs_naics", I could convert HS1(1996) to NAICS(combined). I wonder whether NAICS(combined) refers to NAICS2017.  NAICS had different versions, but I could not find the version which NAICS(combined) refers to in the help document.

Thank you! Looking forward to hearing from you.

Best regards,
Liqizheng

**Comment by stevenliaotw** [comment]
Hi Liqizheng, 

"NAICS combined" includes unique concordances across all existing NAICS (currently, NAICS2002, NAICS2007, NAICS2012, NAICS2017). The same logic applies to other classifications (e.g., HS). Note that version-specific NAICS concordance is currently supported in the developer's version of the package. Installation instructions here <https://github.com/insongkim/concordance#installation-instructions>.

If you know the specific year/version of NAICS that you need as an output, I would just use that. Also, I would just use the general wrapper function ``concord`` instead ``concord_hs_naics``.

Best,
Steven
