### ISSUE TITLE
concord_hs_isic function missing

### ISSUE THREAD

**Issue by ZhihaoMa** [insongkim/concordance#15]
I noticed that the documentation for the 'concordance' R package on [RDRR](https://rdrr.io/github/insongkim/concordance/man/concord_hs_isic.html) mentions the existence of the concord_hs_isic function, which is designed to convert HS and ISIC Codes. However, when I installed the latest version of the package, I couldn't find this function.

Is the concord_hs_isic function still available in the package, and if so, how can I use it with the latest version? If it has been deprecated or removed, are there any alternative functions or methods for performing HS and ISIC code conversions in the current version of the 'concordance' package?

I appreciate your help in clarifying this issue. Thank you!

**Comment by stevenliaotw** [comment]
Hi Zhihao,

HS-ISIC concordance is currently included in the development version of our package. See installation instructions here <https://github.com/insongkim/concordance#installation-instructions>. Also, you can just use the ``concord`` function, which is a wrapper function for all the pair-wise concordance functions such as ``concord_hs_isic``. Hope this helps! 

Best,
Steven

**Comment by ZhihaoMa** [comment]
Thanks, Steven.

 I'm glad to know that it's still available, and I'll be using it with the development version.
 
Best regards,
Zhihao
