### ISSUE TITLE
concord from HS4 to ISIC4

### ISSUE THREAD

**Issue by Tarekji** [insongkim/concordance#3]
abnormally after an update of R and Rstudio, I noticed that ISIC4 has disappeared from "origin" and "destination" of the function. I used it to switch from HS4 to ISIC4 during the last days, but I can't now. 

thanks for your work, the package really helped me. 
![concord](https://user-images.githubusercontent.com/82983898/115635727-a3ebb280-a30c-11eb-87ce-17bf7de92090.jpeg)

**Comment by stevenliaotw** [comment]
ISIC has only been supported in the development version.  Reinstalling the development version as described here <https://github.com/insongkim/concordance#installation-instructions> resolved the issue.
