### ISSUE TITLE
Suspect concordance from ISIC3 (2 digits) to ISIC4 (2 digits)

### ISSUE THREAD

**Issue by alessiolombini** [insongkim/concordance#4]
Hello, 
When I try to harmonize the **products 28** (Manufacture of fabricated metal products, except machinery and equipment) and **29** (Manufacture of machinery and equipment n.e.c.)  from ISIC 3 to ISIC 4 (at two digits levels), they are both converted as product 33 (Repair and installation of machinery and equipment). 
However, according to the ISIC Revision available in [ILO stat](https://ilostat.ilo.org/resources/concepts-and-definitions/classification-economic-activities/), the sectors ISIC 4 having the same label are 25 and 28 respectively. 

Therefore, I would like to ask which conversion it would be more appropriate. 
Thanks in advance

**Comment by stevenliaotw** [comment]
Thank you for raising this important question. I apologize for the late response -- Github has been sending notifications to my old e-mail and thus I wasn't aware of this open issue. 

So the reason for this difference is a combination of the following (1) our concordance is done at the most disaggregated level of the classification codes, e.g., 4 digits for ISIC, and (2) there could also be 1-to-n matches. Type the below to see our full concordance table between ISIC 3 and 4.
```r
data("isic4_isic3")
```

As a result, when you concord, e.g., ISIC3 code 28 to ISIC4, a larger proportion (around 31%) of ISIC3 28 4-digit products are matched to ISIC 33. See below. Setting the option ``all = FALSE'' will then only return the _mode_ match.
```r
concord(sourcevar = c("28", "29"), origin = "ISIC3", destination = "ISIC4", dest.digit = 2, all = TRUE)
```
```
$`28`
$`28`$match
[1] "33" "25" "95" "01" "18" "28" "32" "80"

$`28`$weight
[1] 0.30769231 0.26923077 0.23076923 0.03846154 0.03846154 0.03846154 0.03846154 0.03846154


$`29`
$`29`$match
[1] "33" "28" "27" "25" "30" "32"

$`29`$weight
[1] 0.50000000 0.36206897 0.05172414 0.03448276 0.03448276 0.01724138
```

Thus, to reduce potential differences in label names, my recommendation is to supply the most fine-grained input codes available. Additionally, you can also check and utilize the weights above by setting ``all = TRUE``. 

Thanks for your interest in our package. Hope this helps clarify things. Please let me know if you have any further questions. If not, I will close the issue.
