### ISSUE TITLE
New HS 2022

### ISSUE THREAD

**Issue by Chugua** [insongkim/concordance#8]
Hi,
as you know new version (2022) of HS has been released. 
So, are you going to update your package or I should switch to another one?

**Comment by stevenliaotw** [comment]
Remaining to-dos to completely close issue #8:  

- [x] HS6 description files for ``get_desc``
- [x] Official HS6 concordances to SITC and BEC <https://unstats.un.org/unsd/classifications/Econ>
- [x] Various "bridge" concordances: HS6-->HS3--ISIC <https://github.com/insongkim/concordance/blob/master/data-raw/clean-hs-to-isic.R> and HS6-->HS5-->NAICS <https://github.com/insongkim/concordance/blob/master/data-raw/clean-hs-to-naics.R>
- [x] Update main concordance wrapper function ``concord`` and remaining ``get_***`` functions

**Comment by stevenliaotw** [comment]
@tomoya-sasaki Would you be interested in contributing by working on the remaining HS6 update items above? The recent pull request here <https://github.com/insongkim/concordance/pull/11> will give you a sense of how updates are generally done. We can also set up a Zoom chat to talk about details. Let me know!

**Comment by tomoya-sasaki** [comment]
Thank you @stevenliaotw for letting me know about this and I am sorry for the late reply. I am interested in working on this but would like to know the timeline. I think having a Zoom call would be great. Thank you so much!

**Comment by stevenliaotw** [comment]
@tomoya-sasaki No worries! @haocharliezhang is now working on this, so we are good at this time. If something comes up that we might need your help with, I'll let you know again!

**Comment by tomoya-sasaki** [comment]
Sounds good, thanks!

**Comment by sojunp** [comment]
@stevenliaotw My sincere apologies that I've missed this thread! I'll also incorporate the new version of HS6 into IPC and USPC concordance if desired and keep you all posted on the update.

**Comment by stevenliaotw** [comment]
No worries — sounds good!

**Comment by stevenliaotw** [comment]
HS6 (2022) is now incorporated in the developer's version of our package. Installation instructions here: https://github.com/insongkim/concordance#installation-instructions
