### ISSUE TITLE
concord_hs_isic is not working

### ISSUE THREAD

**Issue by ethai98** [insongkim/concordance#9]
Hello,

I'm trying to convert HS codes into ISIC codes, but I'm getting an error message from this line of code: 

`concord_hs_isic(sourcevar = c("391723", "391729"), origin = "HS2", destination = "ISIC3.1")`

Output: 
`Error: 'hs2_isic3' is not an exported object from 'namespace:concordance'`

Could you look into this, please? Thank you!

**Comment by stevenliaotw** [comment]
Hi Eric,

ISIC is currently supported in the developer's version. Follow installation instructions here <https://github.com/insongkim/concordance#installation-instructions>. It should work afterward. Also, I would simply use the ```concord``` function, which wraps all the sub-concordance functions, e.g., ```concord_hs_isic```. 

Best,
Steven

**Comment by ethai98** [comment]
Hi Steven,

Thanks for your quick response. I downloaded concordance package per your instruction, but I'm still getting the error that "Error in concord(sourcevar = HS5, origin = "HS5", destination = "ISIC3",  : 
  Concordance not supported" using the following code":

```
HS5<- as.vector(HS17_HS12$`Product Code`)

concord(sourcevar = HS5,
        origin = "HS5",
        destination = "ISIC3",
        dest.digit = 4,
        all = TRUE)
```

Alternatively, how may I access the concordance between HS5 to ISIC3? I think it would be an easier solution for my immediate needs. I notice that the WITS does not provide a concordance from HS5 to ISIC3, but it seems like the concordance package has such concordance table as seen [here](https://rdrr.io/github/insongkim/concordance/man/hs5_isic3.html). 

Best regards,
Eric Thai

**Comment by stevenliaotw** [comment]
Hi Eric,

No problem. Please make sure that you "uninstall the package, restart R, and then reinstall the developer version." This usually solves the issue for others.  The code ```data("hs5_isic3")``` will give you the actual concordance table dataframe. The file here <https://github.com/insongkim/concordance/blob/master/data-raw/clean-hs-to-isic.R> documents how we created the concordance. Hope this helps!

Best,
Steven

**Comment by ethai98** [comment]
Hi Steven,

Thank you for the prompt response and for your help! 

Best regards,
Eric
